services:
- type: cron
  name: woocommerce-redirect-matcher-gsc-v3
  env: python
  schedule: "0 5 * * *"
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python match_woocommerce_redirect_matcher_gsc_v3.py"
  envVars:
    - key: GSC_SITE_URL
      value: sc-domain:prodesco.es
    - key: SOURCE_SPREADSHEET_ID
      value: 1cG_3QMYu1iM4TPwu6FILVFFoZy3v4kw6Iy-SwyQBtzQ
    - key: OUTPUT_TAB_MATCHES
      value: Matches
    - key: OUTPUT_TAB_UNMATCHED
      value: Unmatched
    - key: OUTPUT_TAB_HTACCESS
      value: Redirects_301
    - key: DATA_STATE
      value: final
    - key: GSC_SEARCH_TYPE
      value: web
    - key: DATE_RANGE_MONTHS
      value: "16"
    - key: END_DATE_OFFSET_DAYS
      value: "2"
    - key: MAX_QUERIES_PER_URL
      value: "200"
    - key: URL_WEIGHT
      value: "0.25"
    - key: QUERY_WEIGHT
      value: "0.75"
    - key: MIN_SCORE
      value: "70"
    - key: MIN_MARGIN
      value: "5"
    - key: LANG_HINTS
      value: es,en
    - key: USE_NGRAMS
      value: "3"
    - key: MAX_CANDIDATES
      value: "500"
    - key: WRITE_DEBUG_SHEET
      value: "1"
    - key: LANG_ENFORCE
      value: "1"
    - key: TYPE_ENFORCE
      value: "1"
    - key: LAST_SEGMENT_BOOST
      value: "0.10"
    - key: EXACT_SLUG_BOOST
      value: "0.15"
    - key: SKU_BOOST
      value: "0.12"
    - key: MODEL_TOKEN_BOOST
      value: "0.08"
    # Añadir en Render:
    # - key: GOOGLE_CREDENTIALS_JSON
    # - key: WOO_BASE_URL (https://prodesco.es)
    # - key: WOO_CONSUMER_KEY
    # - key: WOO_CONSUMER_SECRET
